import { test, expect } from '@playwright/test';
import { login, databaseRows, captureErrors } from './helpers.js';

test('admin creates and edits member, API key persists, deletion cleans the account', async ({ page }) => {
    test.setTimeout(90_000);
    const errors = captureErrors(page);
    await login(page);
    await page.goto('/en/admin/users');
    await page.getByRole('button', { name: /Add User|Tambah User/, exact: true }).click();
    const form = page.locator('form').filter({ has: page.locator('input[type="email"]') });
    await form.locator('input[type="text"]').fill('QA Created Member');
    await form.locator('input[type="email"]').fill('created@dashboard-e2e.test');
    await form.locator('input[type="password"]').fill('Created-E2e-Only!');
    const created = page.waitForResponse(response => response.url().endsWith('/api/a/u') && response.request().method() === 'POST');
    await form.locator('button[type="submit"]').click();
    expect((await created).status()).toBe(201);
    const user = databaseRows('users', { email: 'created@dashboard-e2e.test' })[0];
    expect(user.name).toBe('QA Created Member');
    const row = page.getByRole('row').filter({ hasText: 'created@dashboard-e2e.test' });
    await row.getByRole('button', { name: 'Edit', exact: true }).click();
    await form.locator('input[type="text"]').fill('QA Updated Member');
    const updated = page.waitForResponse(response => response.url().endsWith(`/api/a/u/${user.id}`) && response.request().method() === 'PUT');
    await form.locator('button[type="submit"]').click();
    expect((await updated).status()).toBe(200);
    await expect(row).toContainText('QA Updated Member');
    await row.getByRole('button', { name: 'API Key', exact: true }).click();
    const keyCreated = page.waitForResponse(response => response.url().endsWith('/api/k/create'));
    await page.getByRole('button', { name: /Generate.*Key|Buat.*Key|Create.*Key/i }).click();
    expect((await keyCreated).status()).toBe(201);
    expect(databaseRows('api_keys', { user_id: user.id })).toHaveLength(1);
    const originalKey = databaseRows('api_keys', { user_id: user.id })[0];
    expect((await page.request.get('/v1/models', { headers: { Authorization: `Bearer ${originalKey.key}` } })).status()).toBe(200);
    const disabledKey = page.waitForResponse(response => response.url().endsWith(`/api/k/toggle/${originalKey.id}`));
    await page.getByRole('button', { name: 'Nonaktifkan', exact: true }).click();
    expect((await disabledKey).status()).toBe(200);
    expect((await page.request.get('/v1/models', { headers: { Authorization: `Bearer ${originalKey.key}` } })).status()).toBe(401);
    const enabledKey = page.waitForResponse(response => response.url().endsWith(`/api/k/toggle/${originalKey.id}`));
    await page.getByRole('button', { name: 'Aktifkan', exact: true }).click();
    expect((await enabledKey).status()).toBe(200);
    await page.getByRole('button', { name: 'Regenerate', exact: true }).click();
    const regeneratedKey = page.waitForResponse(response => response.url().endsWith(`/api/k/regen/${originalKey.id}`));
    await page.getByRole('dialog').filter({ has: page.getByRole('heading', { name: 'Regenerate API Key?', exact: true }) }).getByRole('button', { name: 'Regenerate', exact: true }).click();
    expect((await regeneratedKey).status()).toBe(200);
    const replacementKey = databaseRows('api_keys', { id: originalKey.id })[0];
    expect(replacementKey.key).not.toBe(originalKey.key);
    expect((await page.request.get('/v1/models', { headers: { Authorization: `Bearer ${originalKey.key}` } })).status()).toBe(401);
    expect((await page.request.get('/v1/models', { headers: { Authorization: `Bearer ${replacementKey.key}` } })).status()).toBe(200);
    await page.goto('/en/admin/users');
    await expect(row).toContainText('QA Updated Member');
    await row.getByRole('button', { name: /Delete|Hapus/, exact: true }).click();
    const deleted = page.waitForResponse(response => response.url().endsWith(`/api/a/u/${user.id}`) && response.request().method() === 'DELETE');
    await page.getByRole('dialog').getByRole('button', { name: 'Delete', exact: true }).click();
    expect((await deleted).status()).toBe(200);
    expect(databaseRows('users', { id: user.id })).toHaveLength(0);
    expect(databaseRows('api_keys', { user_id: user.id })).toHaveLength(0);
    expect(errors).toEqual([]);
});

test('pricing changes flow into member checkout catalog and wallet top-up persists ledger', async ({ page }) => {
    const errors = captureErrors(page);
    await login(page);
    await page.goto('/en/admin/settings');
    const row = page.getByRole('row').filter({ hasText: /1 Hari|1 Day/ });
    await row.locator('input[type="number"]').first().fill('6500');
    const saved = page.waitForResponse(response => response.url().endsWith('/api/pricing/durations/bulk') && response.request().method() === 'PATCH');
    await page.getByRole('button', { name: 'Save packages (1)', exact: true }).click();
    await page.getByRole('dialog').getByRole('button', { name: 'Save 1 rows', exact: true }).click();
    expect((await saved).status()).toBe(200);
    const catalog = await page.request.get('/api/pricing/catalog');
    expect((await catalog.json()).duration_packages['1_day'].price_idr).toBe(6500);
    const member = databaseRows('users', { email: 'other@dashboard-e2e.test' })[0];
    const before = databaseRows('wallets', { user_id: member.id })[0].balance_microusd;
    const topup = page.locator('section').filter({ has: page.getByRole('heading', { name: 'Top up PAYG wallet' }) });
    await topup.locator('input').nth(0).fill(String(member.id));
    await topup.locator('input').nth(1).fill('2.5');
    await topup.locator('input').nth(2).fill('QA wallet ledger verification');
    const toppedUp = page.waitForResponse(response => response.url().endsWith('/api/pricing/wallet/topup'));
    await topup.getByRole('button').click();
    expect((await toppedUp).status()).toBe(200);
    expect(databaseRows('wallets', { user_id: member.id })[0].balance_microusd).toBe(before + 2500000);
    expect(databaseRows('wallet_transactions', { user_id: member.id }).some(row => row.description === 'QA wallet ledger verification')).toBe(true);
    await page.reload();
    await expect(row.locator('input[type="number"]').first()).toHaveValue('6500');
    expect(errors).toEqual([]);
});
