import { test, expect } from '@playwright/test';
import { login, databaseRows, captureErrors } from './helpers.js';

test('admin creates and edits member, API key persists, deletion cleans the account', async ({ page }) => {
    test.setTimeout(90_000);
    const errors = captureErrors(page);
    await login(page);
    await page.goto('/en/admin/users');
    await page.getByRole('button', { name: /Add User|Tambah User/, exact: true }).click();
    const form = page.locator('form').filter({ has: page.locator('input[type="email"]') });
    await form.locator('input[type="text"]').fill('QA Created Member');
    await form.locator('input[type="email"]').fill('created@dashboard-e2e.test');
    await form.locator('input[type="password"]').fill('Created-E2e-Only!');
    await form.getByRole('button', { name: /API Eksternal/ }).click();
    const created = page.waitForResponse(response => response.url().endsWith('/api/a/u') && response.request().method() === 'POST');
    await form.locator('button[type="submit"]').click();
    expect((await created).status()).toBe(201);
    const user = databaseRows('users', { email: 'created@dashboard-e2e.test' })[0];
    expect(user.name).toBe('QA Created Member');
    const row = page.getByRole('row').filter({ hasText: 'created@dashboard-e2e.test' });
    await row.getByRole('button', { name: 'Edit', exact: true }).click();
    await form.locator('input[type="text"]').fill('QA Updated Member');
    const updated = page.waitForResponse(response => response.url().endsWith(`/api/a/u/${user.id}`) && response.request().method() === 'PUT');
    await form.locator('button[type="submit"]').click();
    expect((await updated).status()).toBe(200);
    await expect(row).toContainText('QA Updated Member');
    await page.goto('/en/admin/api-keys');
    await page.locator('#ak-user').selectOption(String(user.id));
    await page.locator('#ak-name').fill('QA lifecycle key');
    const keyCreated = page.waitForResponse(response => response.url().endsWith('/api/k/create'));
    await page.locator('form button[type="submit"]').click();
    const keyResponse = await keyCreated;
    expect(keyResponse.status()).toBe(201);
    const originalSecret = (await keyResponse.json()).key;
    expect(databaseRows('api_keys', { user_id: user.id })).toHaveLength(1);
    const originalKey = databaseRows('api_keys', { user_id: user.id })[0];
    expect(JSON.stringify(originalKey).includes(originalSecret)).toBe(false);
    expect((await (await page.request.get('/api/k/list')).text()).includes(originalSecret)).toBe(false);
    expect((await page.request.get('/v1/models', { headers: { Authorization: `Bearer ${originalSecret}` } })).status()).toBe(200);
    const disabledKey = page.waitForResponse(response => response.url().endsWith(`/api/k/toggle/${originalKey.id}`));
    await page.getByRole('button', { name: 'Disable', exact: true }).click();
    expect((await disabledKey).status()).toBe(200);
    expect((await page.request.get('/v1/models', { headers: { Authorization: `Bearer ${originalSecret}` } })).status()).toBe(401);
    const enabledKey = page.waitForResponse(response => response.url().endsWith(`/api/k/toggle/${originalKey.id}`));
    await page.getByRole('button', { name: 'Enable', exact: true }).click();
    expect((await enabledKey).status()).toBe(200);
    await page.getByRole('button', { name: 'Regenerate', exact: true }).click();
    const regeneratedKey = page.waitForResponse(response => response.url().endsWith(`/api/k/regen/${originalKey.id}`));
    await page.getByRole('dialog').getByRole('button', { name: 'Regenerate', exact: true }).click();
    const regeneratedResponse = await regeneratedKey;
    expect(regeneratedResponse.status()).toBe(200);
    const replacementSecret = (await regeneratedResponse.json()).key;
    expect(replacementSecret).not.toBe(originalSecret);
    expect((await page.request.get('/v1/models', { headers: { Authorization: `Bearer ${originalSecret}` } })).status()).toBe(401);
    expect((await page.request.get('/v1/models', { headers: { Authorization: `Bearer ${replacementSecret}` } })).status()).toBe(200);
    await page.goto('/en/admin/users');
    await expect(row).toContainText('QA Updated Member');
    await row.getByRole('button', { name: /Delete|Hapus/, exact: true }).click();
    const deleted = page.waitForResponse(response => response.url().endsWith(`/api/a/u/${user.id}`) && response.request().method() === 'DELETE');
    await page.getByRole('dialog').getByRole('button', { name: 'Delete', exact: true }).click();
    expect((await deleted).status()).toBe(200);
    expect(databaseRows('users', { id: user.id })).toHaveLength(0);
    expect(databaseRows('api_keys', { user_id: user.id })).toHaveLength(0);
    expect(errors).toEqual([]);
});

test('pricing changes persist and reach the member checkout catalog', async ({ page }) => {
    const errors = captureErrors(page);
    await login(page);
    await page.goto('/en/admin/settings');
    await page.getByRole('tab', { name: /Duration/ }).click();
    const row = page.getByRole('row').filter({ hasText: /1 Hari|1 Day/ });
    await row.locator('input[type="number"]').first().fill('6500');
    const saved = page.waitForResponse(response => response.url().endsWith('/api/pricing/durations/bulk') && response.request().method() === 'PATCH');
    await page.getByRole('button', { name: 'Save packages (1)', exact: true }).click();
    await page.getByRole('dialog').getByRole('button', { name: 'Save 1 rows', exact: true }).click();
    expect((await saved).status()).toBe(200);
    const catalog = await page.request.get('/api/pricing/catalog');
    expect((await catalog.json()).duration_packages['1_day'].price_idr).toBe(6500);
    await page.reload();
    await page.getByRole('tab', { name: /Duration/ }).click();
    await expect(row.locator('input[type="number"]').first()).toHaveValue('6500');
    expect(errors).toEqual([]);
});
