import { test, expect } from '@playwright/test';
import { login, databaseRows, captureErrors } from './helpers.js';

test('admin-created model persists and public catalog respects enablement without fake availability', async ({ page }) => {
    const errors = captureErrors(page);
    await login(page);
    await page.goto('/en/admin/ai');
    await page.getByRole('button', { name: 'New model', exact: true }).click();
    const editor = page.locator('form').filter({ has: page.getByLabel('Model ID', { exact: true }) });
    await editor.getByLabel('Provider connection', { exact: true }).selectOption('qa-local');
    await editor.getByLabel('Model ID', { exact: true }).fill('qa-browser-model');
    await editor.getByLabel('Upstream model ID', { exact: true }).fill('qa-browser-model');
    await editor.getByLabel('Display name', { exact: true }).fill('QA browser model');
    await editor.getByLabel('Providers', { exact: true }).fill('QA provider');
    await editor.getByLabel('Category', { exact: true }).fill('chat');
    await editor.getByLabel('Tier', { exact: true }).fill('Original');
    await editor.getByLabel('Context window (tokens)', { exact: true }).fill('64000');
    await editor.getByLabel('Description (Indonesian)', { exact: true }).fill('Deskripsi model dari tes browser nyata.');
    await editor.getByLabel('Description (English)', { exact: true }).fill('Description persisted by the real browser.');
    await editor.getByLabel('Capabilities (comma separated)', { exact: true }).fill('chat');
    await editor.getByLabel('Input modalities', { exact: true }).fill('text');
    await editor.getByLabel('Output modalities', { exact: true }).fill('text');
    await editor.getByLabel('Input', { exact: true }).fill('0.4');
    await editor.getByLabel('Output', { exact: true }).fill('1.2');
    await editor.getByLabel('Active', { exact: true }).check();
    const created = page.waitForResponse(response => response.url().endsWith('/api/admin/ai/models') && response.request().method() === 'POST');
    await editor.getByRole('button', { name: /Save model|Create model/, exact: true }).click();
    expect((await created).status()).toBe(201);
    const model = databaseRows('ai_model_profiles', { model_id: 'qa-browser-model' })[0];
    expect(model.is_available).toBe(0);
    await page.goto('/en/models');
    await page.locator('[data-model-search]').fill('qa-browser-model');
    await expect(page.locator('[data-model-card]:visible')).toHaveCount(1);
    await expect(page.getByText('Description persisted by the real browser.', { exact: true })).toBeVisible();
    await expect(page.locator('[data-model-card]:visible')).toContainText('$0.400');
    await expect(page.locator('[data-model-card]:visible')).toContainText('$1.200');
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(page.locator('[data-model-card]:visible')).toBeInViewport();
    await page.locator('[data-model-filter-toggle]').click();
    await page.locator('[data-model-billing-check][value="payg"]').check();
    await page.keyboard.press('Escape');
    await expect(page.locator('[data-model-card]:visible')).toBeInViewport();
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.goto('/en/admin/ai');
    const row = page.getByRole('row').filter({ hasText: 'qa-browser-model' });
    await row.getByRole('button', { name: 'Disable', exact: true }).click();
    const confirm = page.getByRole('dialog');
    if (await confirm.count()) await confirm.getByRole('button', { name: /Disable|Confirm/ }).click();
    await expect.poll(() => databaseRows('ai_model_profiles', { id: model.id })[0].is_enabled).toBe(0);
    await page.goto('/en/models');
    await expect(page.locator('[data-model-card]').filter({ hasText: 'qa-browser-model' })).toHaveCount(0);
    expect(errors).toEqual([]);
});
