import { test, expect } from '@playwright/test';
import { login, newSession, databaseRows, captureErrors } from './helpers.js';

test('member ticket and feedback reach admin, replies persist, inbox read state survives reload', async ({ page, browser }) => {
    test.setTimeout(90_000);
    const errors = captureErrors(page);
    await login(page, 'member');
    await page.goto('/en/bantuan');
    const ticketForm = page.locator('form').filter({ has: page.getByLabel('Subject', { exact: false }) });
    const subject = 'QA billing support workflow';
    await ticketForm.getByLabel('Subject', { exact: false }).fill(subject);
    await ticketForm.getByLabel('Detail', { exact: false }).fill('Please review the integration payment state for this QA account.');
    const created = page.waitForResponse(response => response.url().endsWith('/api/support/tickets') && response.request().method() === 'POST');
    await ticketForm.getByRole('button', { name: 'Create ticket', exact: true }).click();
    expect((await created).status()).toBe(201);
    const ticket = databaseRows('support_tickets', { subject })[0];
    expect(ticket.status).toBe('open');
    expect(databaseRows('support_messages', { ticket_id: ticket.id })).toHaveLength(1);

    const feedbackForm = page.locator('form').filter({ has: page.getByRole('button', { name: 'Send feedback', exact: true }) });
    await feedbackForm.locator('textarea').fill('QA workflow feedback recorded through the real browser interface.');
    const feedback = page.waitForResponse(response => response.url().endsWith('/api/feedback') && response.request().method() === 'POST');
    await feedbackForm.getByRole('button', { name: 'Send feedback', exact: true }).click();
    expect((await feedback).status()).toBe(201);
    expect(databaseRows('feedback', { message: 'QA workflow feedback recorded through the real browser interface.' })).toHaveLength(1);

    const admin = await newSession(browser, 'admin');
    await admin.page.goto('/en/admin/content');
    await admin.page.getByRole('tab', { name: 'Support tickets', exact: true }).click();
    await admin.page.getByRole('button').filter({ hasText: subject }).click();
    const adminUser = databaseRows('users', { email: 'admin@dashboard-e2e.test' })[0];
    await admin.page.getByRole('combobox', { name: 'Status', exact: true }).selectOption('in_progress');
    await admin.page.getByRole('combobox', { name: 'Assigned admin', exact: true }).selectOption(String(adminUser.id));
    await admin.page.getByRole('button', { name: 'Review status update', exact: true }).click();
    const assigned = admin.page.waitForResponse(response => response.url().endsWith(`/api/admin/support/tickets/${ticket.id}`) && response.request().method() === 'PATCH');
    await admin.page.getByRole('dialog').getByRole('button', { name: 'Update ticket', exact: true }).click();
    expect((await assigned).status()).toBe(200);
    expect(databaseRows('support_tickets', { id: ticket.id })[0]).toMatchObject({ assigned_to: adminUser.id, status: 'in_progress' });
    await admin.page.getByLabel('Reply to member', { exact: true }).fill('QA administrator reply saved to the support conversation.');
    const replied = admin.page.waitForResponse(response => response.url().endsWith(`/api/admin/support/tickets/${ticket.id}/replies`));
    await admin.page.getByRole('button', { name: 'Send reply', exact: true }).click();
    expect((await replied).status()).toBe(201);
    expect(databaseRows('support_messages', { ticket_id: ticket.id })).toHaveLength(2);
    await page.reload();
    await page.getByRole('button').filter({ hasText: subject }).click();
    await expect(page.getByText('QA administrator reply saved to the support conversation.', { exact: true })).toBeVisible();

    await page.goto('/en/notifications');
    const readAll = page.getByRole('button', { name: /Mark all.*read/ });
    await expect(readAll).toBeVisible();
    const read = page.waitForResponse(response => response.url().includes('/api/notifications/read-all'));
    await readAll.click();
    expect((await read).status()).toBe(200);
    await page.reload();
    await expect(readAll).toHaveCount(0);
    const member = databaseRows('users', { email: 'member@dashboard-e2e.test' })[0];
    const notifications = databaseRows('notifications', { user_id: member.id });
    expect(notifications.some(notification => notification.kind === 'support' && JSON.parse(notification.metadata).ticket_id === ticket.id)).toBe(true);
    expect(notifications.every(notification => notification.read_at !== null)).toBe(true);
    await page.getByRole('link').filter({ hasText: 'New support reply' }).click();
    await expect(page).toHaveURL(`/en/bantuan?ticket=${ticket.id}`);
    await expect(page.getByText('QA administrator reply saved to the support conversation.', { exact: true })).toBeVisible();
    const replyForm = page.locator('form').filter({ has: page.getByRole('button', { name: 'Send reply', exact: true }) });
    await replyForm.locator('textarea').fill('QA member follow-up keeps the whole conversation visible.');
    const followUp = page.waitForResponse(response => response.url().endsWith(`/api/support/tickets/${ticket.id}/replies`));
    await replyForm.getByRole('button', { name: 'Send reply', exact: true }).click();
    expect((await followUp).status()).toBe(201);
    expect(databaseRows('support_messages', { ticket_id: ticket.id })).toHaveLength(3);
    await expect(page.getByText('QA member follow-up keeps the whole conversation visible.', { exact: true })).toBeVisible();
    await expect(page.getByText('QA administrator reply saved to the support conversation.', { exact: true })).toBeVisible();
    await page.reload();
    await expect(page.getByText('QA member follow-up keeps the whole conversation visible.', { exact: true })).toBeVisible();
    const other = await newSession(browser, 'other');
    await other.page.goto(`/en/bantuan?ticket=${ticket.id}`);
    await expect(other.page.getByText('Ticket could not be opened', { exact: true })).toBeVisible();
    await expect(other.page.getByText('QA administrator reply saved to the support conversation.', { exact: true })).toHaveCount(0);
    await other.context.close();
    await admin.page.getByRole('tab', { name: 'Feedback', exact: true }).click();
    const feedbackRow = admin.page.getByRole('row').filter({ hasText: 'QA workflow feedback recorded through the real browser interface.' });
    await feedbackRow.getByRole('button', { name: 'Moderate', exact: true }).click();
    const moderation = admin.page.locator('form').filter({ has: admin.page.getByRole('textbox', { name: 'Admin note', exact: true }) });
    await moderation.getByRole('combobox', { name: 'Status', exact: true }).selectOption('reviewed');
    await moderation.getByRole('checkbox', { name: 'Approved testimonial', exact: true }).check();
    await moderation.getByRole('textbox', { name: 'Admin note', exact: true }).fill('QA moderation decision persisted.');
    await moderation.getByRole('button', { name: 'Review change', exact: true }).click();
    const moderated = admin.page.waitForResponse(response => /\/api\/admin\/feedback\/\d+$/.test(response.url()) && response.request().method() === 'PATCH');
    await admin.page.getByRole('dialog').getByRole('button', { name: 'Save decision', exact: true }).click();
    expect((await moderated).status()).toBe(200);
    expect(databaseRows('feedback', { message: 'QA workflow feedback recorded through the real browser interface.' })[0])
        .toMatchObject({ status: 'reviewed', is_testimonial: 1, admin_note: 'QA moderation decision persisted.' });
    await admin.page.getByRole('tab', { name: 'Broadcasts', exact: true }).click();
    await admin.page.getByRole('textbox', { name: 'Title', exact: true }).fill('QA targeted operational update');
    await admin.page.getByRole('textbox', { name: 'Message', exact: true }).fill('A durable broadcast delivered by the real operations workflow.');
    await admin.page.getByRole('textbox', { name: 'Action URL (optional)', exact: true }).fill('/bantuan');
    await admin.page.getByRole('button', { name: 'Review broadcast', exact: true }).click();
    const broadcast = admin.page.waitForResponse(response => response.url().endsWith('/api/admin/engagement/broadcasts'));
    await admin.page.getByRole('dialog').getByRole('button', { name: 'Send broadcast', exact: true }).click();
    expect((await broadcast).status()).toBe(201);
    const delivered = databaseRows('notifications', { title: 'QA targeted operational update' });
    expect(delivered.map(notification => notification.user_id).sort()).toEqual(databaseRows('users', { role: 'member' }).map(user => user.id).sort());
    await page.goto('/en/notifications');
    await expect(page.getByRole('link').filter({ hasText: 'QA targeted operational update' })).toHaveAttribute('href', '/en/bantuan');
    expect(errors).toEqual([]);
    await admin.context.close();
});
